version: '3.4'

volumes:
  pg_project:

services:
  reactpro:
    image: kirillkus/react
    ports:
      - "8082:8080"
    build:
      context: .
    container_name: react
    environment:
      - SPRING_R2DBC_URL=r2dbc:postgresql://host.docker.internal:5432/postgres
      - JAVA_OPTS="-XX:+UseG1GC -XX:MaxRAMPercentage=75"
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=broker:29092

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    restart: always
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
      image: confluentinc/cp-kafka:7.3.0
      restart: always
      container_name: broker
      ports:
        - "9092:9092"
      depends_on:
        - zookeeper
      environment:
        KAFKA_BROKER_ID: 1
        KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
        KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
