version: '3.4'

services:
  graphQL:
    image: graphql
    ports:
      - "8085:8081"
    build:
      context: .
    container_name: graphql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5432/Klinika
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none